#!/usr/bin/env bash
# Change your home IP address

grep -v -e "facebook.com" -e "localhost" /etc/hosts > /tmp/hosts && sudo mv /tmp/hosts /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
